#!/usr/bin/env ruby

$:.push('lib', '../lib')

require 'skype'
Skype.DEBUG = true
skype = Skype.new('ruby-skype-test')
skype.connect

puts "Attempting to call the echo service..."
skype.send_raw_command('CALL echo123')
skype.run
