#!/usr/bin/env ruby

# This program simply attaches to Skype and runs an event loop. Can be used as a starting point, or a way to
# listen for new update commands that we may not know about yet.

$:.push('lib')

require 'skype'
require 'skype/communication/windows'
Skype.DEBUG = true
comm = Skype::Communication::Windows.new
skype = Skype.new('ruby-skype-listen-in', comm)
skype.connect
puts "Connected using protocol version #{skype.protocol_version}"
skype.run
